approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard
  - code: YN0076
    level: discard
  - code: YN0086
    level: discard

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@docker/actions-toolkit"
